# See j2objc-gradle's .travis.yml for explanations.

language: objective-c
os: osx
# Add a TEST_DIR=[directory] row for each library (or group of libraries) to test
# Each will be run as an independent, hermetic test on Travis (in parallel when
# resources permit)
env:
  - TEST_DIR=com.google.code.gson-gson
  - TEST_DIR=org.joda-joda-convert
  - TEST_DIR=joda-time-joda-time
  - TEST_DIR=org.joda-joda-primitives
  - TEST_DIR=org.apache.commons-commons-lang3

matrix:
  allow_failures:
    # Blocked on https://github.com/j2objc-contrib/j2objc-common-libs-e2e-test/issues/40
    - env: TEST_DIR=org.joda-joda-convert
    - env: TEST_DIR=joda-time-joda-time

branches:
  only:
    - master
    - /^release.*$/
    - /^v[0-9].*$/

sudo: false

install:
  - pushd libraryBuilds
  - ./install.sh

# Note the install prep leaves us in the libraryBuilds directory.
script:
  - ./run-test.sh $TEST_DIR
